data = [
{ "brand": "Intel",          "generation": "11th Gen i7",                                                    "model": "i7-11700",                                                   "cores": 8 },
{ "brand": "Intel",          "generation": "11th Gen i9",                                                    "model": "i9-11900T",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "11th Gen i9",                                                    "model": "i9-11900KF",                                                 "cores": 8 },
{ "brand": "Intel",          "generation": "11th Gen i9",                                                    "model": "i9-11900K",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "11th Gen i9",                                                    "model": "i9-11900F",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "11th Gen i9",                                                    "model": "i9-11900",                                                   "cores": 8 },
{ "brand": "Intel",          "generation": "11th Gen i7",                                                    "model": "i7-11700T",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "11th Gen i7",                                                    "model": "i7-11700KF",                                                 "cores": 8 },
{ "brand": "Intel",          "generation": "11th Gen i7",                                                    "model": "i7-11700K",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "11th Gen i7",                                                    "model": "i7-11700F",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "11th Gen i5",                                                    "model": "i5-11600T",                                                  "cores": 6 },
{ "brand": "Intel",          "generation": "11th Gen i5",                                                    "model": "i5-11600KF",                                                 "cores": 6 },
{ "brand": "Intel",          "generation": "11th Gen i5",                                                    "model": "i5-11600K",                                                  "cores": 6 },
{ "brand": "Intel",          "generation": "11th Gen i5",                                                    "model": "i5-11600",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "11th Gen i5",                                                    "model": "i5-11500T",                                                  "cores": 6 },
{ "brand": "Intel",          "generation": "11th Gen i5",                                                    "model": "i5-11500",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "11th Gen i5",                                                    "model": "i5-11400T",                                                  "cores": 6 },
{ "brand": "Intel",          "generation": "11th Gen i5",                                                    "model": "i5-11400F",                                                  "cores": 6 },
{ "brand": "Intel",          "generation": "11th Gen i5",                                                    "model": "i5-11400",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "10th Gen i3",                                                    "model": "i3-10325",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "10th Gen i3",                                                    "model": "i3-10305T",                                                  "cores": 4 },
{ "brand": "Intel",          "generation": "10th Gen i3",                                                    "model": "i3-10305",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "10th Gen i3",                                                    "model": "i3-10105T",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "10th Gen i3",                                                    "model": "i3-10105",                                                   "cores": 8 },
{ "brand": "Intel",          "generation": "10th Gen i3",                                                    "model": "i3-10105F",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "10th Gen i3",                                                    "model": "i3-10100F",                                                  "cores": 4 },
{ "brand": "Intel",          "generation": "10th Gen i9",                                                    "model": "i9-10850K",                                                  "cores": 10 },
{ "brand": "Intel",          "generation": "10th Gen i9",                                                    "model": "i9-10900T",                                                  "cores": 10 },
{ "brand": "Intel",          "generation": "10th Gen i9",                                                    "model": "i9-10900KF",                                                 "cores": 10 },
{ "brand": "Intel",          "generation": "10th Gen i9",                                                    "model": "i9-10900K",                                                  "cores": 10 },
{ "brand": "Intel",          "generation": "10th Gen i9",                                                    "model": "i9-10900F",                                                  "cores": 10 },
{ "brand": "Intel",          "generation": "10th Gen i9",                                                    "model": "i9-10900",                                                   "cores": 10 },
{ "brand": "Intel",          "generation": "10th Gen i7",                                                    "model": "i7-10700T",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "10th Gen i7",                                                    "model": "i7-10700KF",                                                 "cores": 8 },
{ "brand": "Intel",          "generation": "10th Gen i7",                                                    "model": "i7-10700K",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "10th Gen i7",                                                    "model": "i7-10700F",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "10th Gen i7",                                                    "model": "i7-10700",                                                   "cores": 8 },
{ "brand": "Intel",          "generation": "10th Gen i5",                                                    "model": "i5-10600T",                                                  "cores": 6 },
{ "brand": "Intel",          "generation": "10th Gen i5",                                                    "model": "i5-10600KF",                                                 "cores": 6 },
{ "brand": "Intel",          "generation": "10th Gen i5",                                                    "model": "i5-10600K",                                                  "cores": 6 },
{ "brand": "Intel",          "generation": "10th Gen i5",                                                    "model": "i5-10600",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "10th Gen i5",                                                    "model": "i5-10500T",                                                  "cores": 6 },
{ "brand": "Intel",          "generation": "10th Gen i5",                                                    "model": "i5-10500",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "10th Gen i5",                                                    "model": "i5-10400T",                                                  "cores": 6 },
{ "brand": "Intel",          "generation": "10th Gen i5",                                                    "model": "i5-10400F",                                                  "cores": 6 },
{ "brand": "Intel",          "generation": "10th Gen i5",                                                    "model": "i5-10400",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "10th Gen i3",                                                    "model": "i3-10320",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "10th Gen i3",                                                    "model": "i3-10300T",                                                  "cores": 4 },
{ "brand": "Intel",          "generation": "10th Gen i3",                                                    "model": "i3-10300",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "10th Gen i3",                                                    "model": "i3-10100T",                                                  "cores": 4 },
{ "brand": "Intel",          "generation": "10th Gen i3",                                                    "model": "i3-10100",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "9th Gen i9",                                                     "model": "i9-9900KS",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-10980XE",                                                 "cores": 18 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-10940X",                                                  "cores": 14 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-10920X",                                                  "cores": 12 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-10900X",                                                  "cores": 10 },
{ "brand": "Intel",          "generation": "9th Gen i9",                                                     "model": "i9-9900T",                                                   "cores": 8 },
{ "brand": "Intel",          "generation": "9th Gen i9",                                                     "model": "i9-9900",                                                    "cores": 8 },
{ "brand": "Intel",          "generation": "9th Gen i7 ",                                                   "model": "i7-9700T",                                                   "cores": 8 },
{ "brand": "Intel",          "generation": "9th Gen i7 ",                                                   "model": "i7-9700F",                                                   "cores": 8 },
{ "brand": "Intel",          "generation": "9th Gen i7 ",                                                   "model": "i7-9700",                                                    "cores": 8 },
{ "brand": "Intel",          "generation": "9th Gen i5 ",                                                   "model": "i5-9600T",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "9th Gen i5 ",                                                   "model": "i5-9600",                                                    "cores": 6 },
{ "brand": "Intel",          "generation": "9th Gen i5 ",                                                   "model": "i5-9500T",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "9th Gen i5 ",                                                   "model": "i5-9500F",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "9th Gen i5 ",                                                   "model": "i5-9500",                                                    "cores": 6 },
{ "brand": "Intel",          "generation": "9th Gen i5 ",                                                   "model": "i5-9400T",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "9th Gen i3",                                                    "model": "i3-9350K",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "9th Gen i3",                                                    "model": "i3-9320",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "9th Gen i3",                                                    "model": "i3-9300T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "9th Gen i3",                                                    "model": "i3-9300",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "9th Gen i3",                                                    "model": "i3-9100T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "9th Gen i3",                                                    "model": "i3-9100F",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "9th Gen i3",                                                    "model": "i3-9100",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "9th Gen i9",                                                     "model": "i9-9900KF",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "9th Gen i7 ",                                                   "model": "i7-9700KF",                                                  "cores": 8 },
{ "brand": "Intel",          "generation": "9th Gen i5 ",                                                   "model": "i5-9600KF",                                                  "cores": 6 },
{ "brand": "Intel",          "generation": "9th Gen i5 ",                                                   "model": "i5-9400F",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "9th Gen i5 ",                                                   "model": "i5-9400",                                                    "cores": 6 },
{ "brand": "Intel",          "generation": "9th Gen i3",                                                    "model": "i3-9350KF",                                                  "cores": 4 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-9980XE",                                                  "cores": 18 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-9960X",                                                   "cores": 16 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-9940X",                                                   "cores": 14 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-9920X",                                                   "cores": 12 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-9900X",                                                   "cores": 10 },
{ "brand": "Intel",          "generation": "9th Gen i9",                                                     "model": "i9-9900K",                                                   "cores": 8 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-9820X",                                                   "cores": 10 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-9800X",                                                   "cores": 8 },
{ "brand": "Intel",          "generation": "9th Gen i7 ",                                                   "model": "i7-9700K",                                                   "cores": 8 },
{ "brand": "Intel",          "generation": "9th Gen i5 ",                                                   "model": "i5-9600k",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i7 ",                                                   "model": "i7-8700T",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i7 ",                                                   "model": "i7-8700",                                                    "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i7 ",                                                   "model": "i7-8086K",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i5",                                                     "model": "i5-8600T",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i5",                                                     "model": "i5-8600",                                                    "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i5",                                                     "model": "i5-8500T",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i5",                                                     "model": "i5-8500",                                                    "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i5",                                                     "model": "i5-8500",                                                    "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i5",                                                     "model": "i5-8400T",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i5",                                                     "model": "i5-8400",                                                    "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i3",                                                    "model": "i3-8300T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "8th Gen i3",                                                    "model": "i3-8300",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "8th Gen i3",                                                    "model": "i3-8100T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "8th Gen i7 ",                                                   "model": "i7-8700K",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i7 ",                                                   "model": "i7-8700",                                                    "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i5",                                                     "model": "i5-8600K",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i5",                                                     "model": "i5-8400",                                                    "cores": 6 },
{ "brand": "Intel",          "generation": "8th Gen i3",                                                    "model": "i3-8350K",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "8th Gen i3",                                                    "model": "i3-8100",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-7980XE",                                                  "cores": 18 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-7960X",                                                   "cores": 16 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-7940X",                                                   "cores": 14 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-7920X",                                                   "cores": 12 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i9-7900X",                                                   "cores": 10 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-7820X",                                                   "cores": 8 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-7800X",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-7740X",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i5-7640X",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "7th Gen i7 ",                                                   "model": "i7-7700T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "7th Gen i7 ",                                                   "model": "i7-7700K",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "7th Gen i7 ",                                                   "model": "i7-7700",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "7th Gen i5 ",                                                   "model": "i5-7600T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "7th Gen i5 ",                                                   "model": "i5-7600K",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "7th Gen i5 ",                                                   "model": "i5-7600",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "7th Gen i5 ",                                                   "model": "i5-7500T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "7th Gen i5 ",                                                   "model": "i5-7500",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "7th Gen i5 ",                                                   "model": "i5-7400T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "7th Gen i5 ",                                                   "model": "i5-7400",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "7th Gen i3",                                                     "model": "i3-7350K",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "7th Gen i3",                                                     "model": "i3-7320",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "7th Gen i3",                                                     "model": "i3-7300T",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "7th Gen i3",                                                     "model": "i3-7300",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "7th Gen i3",                                                     "model": "i3-7101TE",                                                  "cores": 2 },
{ "brand": "Intel",          "generation": "7th Gen i3",                                                     "model": "i3-7101E",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "7th Gen i3",                                                     "model": "i3-7100T",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "7th Gen i3",                                                     "model": "i3-7100",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-6950X",                                                   "cores": 10 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-6900K",                                                   "cores": 8 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-6850K",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-6800K",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "6th Gen i7",                                                     "model": "i7-6785R",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i5",                                                     "model": "i5-6685R",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i5",                                                     "model": "i5-6585R",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i5",                                                     "model": "i5-6402P",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i3 ",                                                   "model": "i3-6098P",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "6th Gen i7",                                                     "model": "i7-6700T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i7",                                                     "model": "i7-6700K",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i7",                                                     "model": "i7-6700",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i5",                                                     "model": "i5-6600T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i5",                                                     "model": "i5-6600K",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i5",                                                     "model": "i5-6600",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i5",                                                     "model": "i5-6500T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i5",                                                     "model": "i5-6500",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i5",                                                     "model": "i5-6400T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i5",                                                     "model": "i5-6400",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "6th Gen i3 ",                                                   "model": "i3-6320",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "6th Gen i3 ",                                                   "model": "i3-6300T",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "6th Gen i3 ",                                                   "model": "i3-6300",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "6th Gen i3 ",                                                   "model": "i3-6100T",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "6th Gen i3 ",                                                   "model": "i3-6100",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "5th Gen i7",                                                     "model": "i7-5775R",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "5th Gen i7",                                                     "model": "i7-5775C",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "5th Gen i5 ",                                                   "model": "i5-5675R",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "5th Gen i5 ",                                                   "model": "i5-5675C",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "5th Gen i5 ",                                                   "model": "i5-5575R",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4170",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4170T",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4370T",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-5960X",                                                   "cores": 8 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-5930K",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-5820K",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4160",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4160T",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4360T",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4370",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4150",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4150T",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4350",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4350T",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4360",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4460",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4460S",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4460T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4590",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4590S",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4590T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4690",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4690K",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4690S",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4690T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i7",                                                     "model": "i7-4785T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i7",                                                     "model": "i7-4790",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i7",                                                     "model": "i7-4790K",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i7",                                                     "model": "i7-4790S",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i7",                                                     "model": "i7-4790T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4130",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4130T",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4330",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4330T",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i3 ",                                                   "model": "i3-4340",                                                    "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4440",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4440S",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i7",                                                     "model": "i7-4771",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-4820K",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-4930K",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "X-series",                                                      "model": "i7-4960X",                                                   "cores": 6 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4430",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4430S",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4570",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4570R",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4570S",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4570T",                                                   "cores": 2 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4670",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4670K",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4670R",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4670S",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i5",                                                    "model": "i5-4670T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i7",                                                     "model": "i7-4765T",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i7",                                                     "model": "i7-4770",                                                    "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i7",                                                     "model": "i7-4770K",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i7",                                                     "model": "i7-4770R",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i7",                                                     "model": "i7-4770S",                                                   "cores": 4 },
{ "brand": "Intel",          "generation": "4th Gen i7",                                                     "model": "i7-4770T",                                                   "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 9 Processors",                                             "model": "Ryzen 9 5900",                                               "cores": 12 },
{ "brand": "AMD",            "generation": "Ryzen 7 Processors",                                             "model": "Ryzen 7 5800",                                               "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen Threadripper PRO Processors",                              "model": "Ryzen Threadripper PRO 3995WX",                              "cores": 64 },
{ "brand": "AMD",            "generation": "Ryzen Threadripper PRO Processors",                              "model": "Ryzen Threadripper PRO 3975WX",                              "cores": 32 },
{ "brand": "AMD",            "generation": "Ryzen Threadripper PRO Processors",                              "model": "Ryzen Threadripper PRO 3955WX",                              "cores": 16 },
{ "brand": "AMD",            "generation": "Ryzen Threadripper PRO Processors",                              "model": "Ryzen Threadripper PRO 3945WX",                              "cores": 12 },
{ "brand": "AMD",            "generation": "Ryzen 9 Processors",                                             "model": "Ryzen 9 3900",                                               "cores": 12 },
{ "brand": "AMD",            "generation": "Ryzen 7 5000 G-Series Processors with Radeon Graphics",          "model": "Ryzen 7 5700GE",                                             "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen 5 5000 G-Series Processors with Radeon Graphics",          "model": "Ryzen 5 5600GE",                                             "cores": 6 },
{ "brand": "AMD",            "generation": "Ryzen 3 5000 G-Series Processors with Radeon Graphics",          "model": "Ryzen 3 5300G",                                              "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 3 5000 G-Series Processors with Radeon Graphics",          "model": "Ryzen 3 5300GE",                                             "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 7 4000 G-Series Processors with Radeon Graphics",          "model": "Ryzen 7 4700G",                                              "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen 5 4000 G-Series Processors with Radeon Graphics",          "model": "Ryzen 5 4600G",                                              "cores": 6 },
{ "brand": "AMD",            "generation": "Ryzen 5 Processors",                                             "model": "Ryzen 5 3500",                                               "cores": 6 },
{ "brand": "AMD",            "generation": "Ryzen 3 4000 G-Series Processors with Radeon Graphics",          "model": "Ryzen 3 4300G",                                              "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 7 4000 G-Series Processors with Radeon Graphics",          "model": "Ryzen 7 4700GE",                                             "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen 5 4000 G-Series Processors with Radeon Graphics",          "model": "Ryzen 5 4600GE",                                             "cores": 6 },
{ "brand": "AMD",            "generation": "Ryzen 3 4000 G-Series Processors with Radeon Graphics",          "model": "Ryzen 3 4300GE",                                             "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 5 Processors with Radeon Vega Graphics",                   "model": "Ryzen 5 3400GE",                                             "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 3 Processors with Radeon Vega Graphics",                   "model": "Ryzen 3 3200GE",                                             "cores": 4 },
{ "brand": "AMD",            "generation": "Athlon Processors with Radeon Vega Graphics",                    "model": "Athlon 320GE",                                               "cores": 2 },
{ "brand": "AMD",            "generation": "Athlon Processors with Radeon Vega Graphics",                    "model": "Athlon 300GE",                                               "cores": 2 },
{ "brand": "AMD",            "generation": "Athlon 3000 G-Series Processors with Radeon Graphics",           "model": "Athlon Gold 3150GE",                                         "cores": 4 },
{ "brand": "AMD",            "generation": "Athlon 3000 G-Series Processors with Radeon Graphics",           "model": "Athlon Gold 3150G",                                          "cores": 4 },
{ "brand": "AMD",            "generation": "Athlon 3000 G-Series Processors with Radeon Graphics",           "model": "Athlon Silver 3050GE",                                       "cores": 2 },
{ "brand": "AMD",            "generation": "Ryzen 7 Processors",                                             "model": "Ryzen 7 2700E",                                              "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen 5 Processors",                                             "model": "Ryzen 5 2600E",                                              "cores": 6 },
{ "brand": "AMD",            "generation": "Ryzen 5 Processors",                                             "model": "Ryzen 5 2500X",                                              "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 5 Processors with Radeon Vega Graphics",                   "model": "Ryzen 5 2400GE with Radeon RX Vega 11 Graphics",             "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 3 Processors",                                             "model": "Ryzen 3 2300X",                                              "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 3 Processors with Radeon Vega Graphics",                   "model": "Ryzen 3 2200GE with Radeon Vega 8 Graphics",                 "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO 5000 Series Processors",                             "model": "Ryzen 5 PRO 5650G",                                          "cores": 6 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO 5000 Series Processors",                             "model": "Ryzen 5 PRO 5650GE",                                         "cores": 6 },
{ "brand": "AMD",            "generation": "Ryzen 9 PRO Processors",                                         "model": "Ryzen 9 PRO 3900",                                           "cores": 12 },
{ "brand": "AMD",            "generation": "Ryzen 7 PRO Processors",                                         "model": "Ryzen 7 PRO 3700",                                           "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen 7 PRO 5000 Series Processors",                             "model": "Ryzen 7 PRO 5750G",                                          "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen 7 PRO 5000 Series Processors",                             "model": "Ryzen 7 PRO 5750GE",                                         "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen 7 PRO 4000 Series Processors",                             "model": "Ryzen 7 PRO 4750G",                                          "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen 3 PRO 5000 Series Processors",                             "model": "Ryzen 3 PRO 5350G",                                          "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO Processors",                                         "model": "Ryzen 5 PRO 3600",                                           "cores": 6 },
{ "brand": "AMD",            "generation": "Ryzen 7 PRO 4000 Series Processors",                             "model": "Ryzen 7 PRO 4750GE",                                         "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen 3 PRO 5000 Series Processors",                             "model": "Ryzen 3 PRO 5350GE",                                         "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO 4000 Series Processors",                             "model": "Ryzen 5 PRO 4650G",                                          "cores": 6 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO 4000 Series Processors",                             "model": "Ryzen 5 PRO 4650GE",                                         "cores": 6 },
{ "brand": "AMD",            "generation": "Ryzen 3 PRO 4000 Series Processors",                             "model": "Ryzen 3 PRO 4350G",                                          "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 3 PRO 4000 Series Processors",                             "model": "Ryzen 3 PRO 4350GE",                                         "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO Processors with Radeon Vega Graphics",               "model": "Ryzen 5 PRO 3400G",                                          "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO Processors with Radeon Vega Graphics",               "model": "Ryzen 5 PRO 3400GE",                                         "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO 3000 Series Processors",                             "model": "Ryzen 5 PRO 3350G",                                          "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO 3000 Series Processors",                             "model": "Ryzen 5 PRO 3350GE",                                         "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 3 PRO Processors with Radeon Vega Graphics",               "model": "Ryzen 3 PRO 3200G",                                          "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 3 PRO Processors with Radeon Vega Graphics",               "model": "Ryzen 3 PRO 3200GE",                                         "cores": 4 },
{ "brand": "AMD",            "generation": "Athlon PRO 3000 Series Processors",                              "model": "Athlon Gold PRO 3150G",                                      "cores": 4 },
{ "brand": "AMD",            "generation": "Athlon PRO 3000 Series Processors",                              "model": "Athlon Gold PRO 3150GE",                                     "cores": 4 },
{ "brand": "AMD",            "generation": "Athlon PRO 3000 Series Processors",                              "model": "Athlon Silver PRO 3125GE",                                   "cores": 2 },
{ "brand": "AMD",            "generation": "Athlon PRO Processors with Radeon Vega Graphics",                "model": "Athlon PRO 300GE",                                           "cores": 2 },
{ "brand": "AMD",            "generation": "Ryzen 7 PRO Processors",                                         "model": "Ryzen 7 PRO 2700X",                                          "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen 7 PRO Processors",                                         "model": "Ryzen 7 PRO 2700",                                           "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen 7 PRO Processors",                                         "model": "Ryzen 7 PRO 1700X",                                          "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen 7 PRO Processors",                                         "model": "Ryzen 7 PRO 1700",                                           "cores": 8 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO Processors",                                         "model": "Ryzen 5 PRO 2600",                                           "cores": 6 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO Processors",                                         "model": "Ryzen 5 PRO 1600",                                           "cores": 6 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO Processors",                                         "model": "Ryzen 5 PRO 1500",                                           "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO Processors with Radeon Vega Graphics",               "model": "Ryzen 5 PRO 2400G with Radeon Vega 11 Graphics",             "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 5 PRO Processors with Radeon Vega Graphics",               "model": "Ryzen 5 PRO 2400GE with Radeon Vega 11 Graphics",            "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 3 PRO Processors",                                         "model": "Ryzen 3 PRO 1300",                                           "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 3 PRO Processors with Radeon Vega Graphics",               "model": "Ryzen 3 PRO 2200G with Radeon Vega 8 Graphics",              "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 3 PRO Processors with Radeon Vega Graphics",               "model": "Ryzen 3 PRO 2200GE with Radeon Vega 8 Graphics",             "cores": 4 },
{ "brand": "AMD",            "generation": "Ryzen 3 PRO Processors",                                         "model": "Ryzen 3 PRO 1200",                                           "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A12 APU fors",                                      "model": "7th Gen PRO A12-9800 APU",                                   "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A12 APU fors",                                      "model": "7th Gen PRO A12-9800E APU",                                  "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A10 APU fors",                                      "model": "7th Gen PRO A10-9700 APU",                                   "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A10 APU fors",                                      "model": "7th Gen PRO A10-9700E APU",                                  "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A8 APU fors",                                       "model": "7th Gen PRO A8-9600 APU",                                    "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A6 APU fors",                                       "model": "7th Gen PRO A6-9500 APU",                                    "cores": 2 },
{ "brand": "AMD",            "generation": "PRO A-Series A6 APU fors",                                       "model": "7th Gen PRO A6-9500E APU",                                   "cores": 2 },
{ "brand": "AMD",            "generation": "PRO A-Series A12 APU fors",                                      "model": "6th Gen PRO A12-8870 APU",                                   "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A12 APU fors",                                      "model": "6th Gen PRO A12-8870E APU",                                  "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A10 APU fors",                                      "model": "6th Gen PRO A10-8850B APU",                                  "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A10 APU fors",                                      "model": "6th Gen PRO A10-8770 APU",                                   "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A10 APU fors",                                      "model": "6th Gen PRO A10-8770E APU",                                  "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A10 APU fors",                                      "model": "6th Gen PRO A10-8750B APU",                                  "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A8 APU fors",                                       "model": "6th Gen PRO A8-8650B APU",                                   "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A6 APU fors",                                       "model": "6th Gen PRO A6-8570 APU",                                    "cores": 2 },
{ "brand": "AMD",            "generation": "PRO A-Series A6 APU fors",                                       "model": "6th Gen PRO A6-8570E APU",                                   "cores": 2 },
{ "brand": "AMD",            "generation": "PRO A-Series A6 APU fors",                                       "model": "6th Gen PRO A6-8550B APU",                                   "cores": 2 },
{ "brand": "AMD",            "generation": "PRO A-Series A4 APU fors",                                       "model": "6th Gen PRO A4-8350B APU",                                   "cores": 2 },
{ "brand": "AMD",            "generation": "A6-Series APU fors",                                             "model": "A6-6310 with Radeon R4 Graphics",                            "cores": 4 },
{ "brand": "AMD",            "generation": "A6-Series APU fors",                                             "model": "A6-5200 with Radeon HD 8400",                                "cores": 4 },
{ "brand": "AMD",            "generation": "A4-Series APU fors",                                             "model": "A4-7300 with Radeon HD 8470D",                               "cores": 2 },
{ "brand": "AMD",            "generation": "A4-Series APU fors",                                             "model": "A4-5100 with Radeon HD 8330",                                "cores": 4 },
{ "brand": "AMD",            "generation": "A4-Series APU fors",                                             "model": "A4-5000 with Radeon HD 8330",                                "cores": 4 },
{ "brand": "AMD",            "generation": "Business Class -  Phenom X4 Quad-Core",                          "model": "B99",                                                        "cores": 4 },
{ "brand": "AMD",            "generation": "Business Class -  Phenom X4 Quad-Core",                          "model": "B97",                                                        "cores": 4 },
{ "brand": "AMD",            "generation": "Business Class -  Phenom X4 Quad-Core",                          "model": "B95",                                                        "cores": 1 },
{ "brand": "AMD",            "generation": "Business Class -  Phenom X3 Triple-Core",                        "model": "B77",                                                        "cores": 3 },
{ "brand": "AMD",            "generation": "Business Class -  Phenom X3 Triple-Core",                        "model": "B75",                                                        "cores": 3 },
{ "brand": "AMD",            "generation": "Business Class -  Phenom X2 Dual-Core",                          "model": "B60",                                                        "cores": 2 },
{ "brand": "AMD",            "generation": "Business Class -  Phenom X2 Dual-Core",                          "model": "B59",                                                        "cores": 2 },
{ "brand": "AMD",            "generation": "Business Class -  Phenom X2 Dual-Core",                          "model": "B57",                                                        "cores": 2 },
{ "brand": "AMD",            "generation": "Business Class - Quad-Core A10-Series APU fors",                 "model": "A10-6800B with Radeon HD 8670D",                             "cores": 4 },
{ "brand": "AMD",            "generation": "Athlon X4",                                                      "model": "860K",                                                       "cores": 4 },
{ "brand": "AMD",            "generation": "Business Class - Quad-Core A10-Series APU fors",                 "model": "A10-6790B with Radeon HD 8670D",                             "cores": 4 },
{ "brand": "AMD",            "generation": "Business Class - Quad-Core A8-Series APU fors",                  "model": "A8-6500B with Radeon HD 8570D",                              "cores": 4 },
{ "brand": "AMD",            "generation": "Business Class - Dual-Core A6-Series APU fors",                  "model": "A6-6420B with Radeon HD 8470D",                              "cores": 2 },
{ "brand": "AMD",            "generation": "Business Class - Dual-Core A6-Series APU fors",                  "model": "A6-6400B with Radeon HD 8470D",                              "cores": 2 },
{ "brand": "AMD",            "generation": "Sempron",                                                        "model": "2800+",                                                      "cores": 1 },
{ "brand": "AMD",            "generation": "PRO A-Series A10 APU fors",                                      "model": "A10 PRO-7850B with Radeon R7 Graphics",                      "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A10 APU fors",                                      "model": "A10 PRO-7800B with Radeon R7 Graphics",                      "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A8 APU fors",                                       "model": "A8 PRO-7600B with Radeon R7 Graphics",                       "cores": 4 },
{ "brand": "AMD",            "generation": "PRO A-Series A6 APU fors",                                       "model": "A6 PRO-7400B with Radeon R5 Graphics",                       "cores": 2 },
{ "brand": "AMD",            "generation": "PRO A-Series A4 APU fors",                                       "model": "A4 PRO-7350B with Radeon R5 Graphics",                       "cores": 2 },
{ "brand": "AMD",            "generation": "PRO A-Series A4 APU fors",                                       "model": "A4 PRO-7300B with Radeon HD 8470D",                          "cores": 2 },
{ "brand": "AMD",            "generation": "Athlon Processors with Radeon Vega Graphics",                    "model": "Athlon 240GE",                                               "cores": 2 },
{ "brand": "AMD",            "generation": "Athlon Quad-Core APU",                                           "model": "Athlon 5370 APU with Radeon R3 Series",                      "cores": 4 },
{ "brand": "AMD",            "generation": "Athlon PRO Processors with Radeon Vega Graphics",                "model": "Athlon PRO 200GE",                                           "cores": 2 }
]


data.each do |line|
  brand = Brand.find_or_create_by(name: line[:brand])
  generation = brand.generations.find_or_create_by(name: line[:generation])
  generation.processors.find_or_create_by(brand: brand, name: line[:model], cores: line[:cores])
end